const inquirer = require('inquirer');
exports.run = async (fun, opt, soc) => {
  inquirer.prompt([{
    type: 'list',
    name: 'item',
    message: 'Choose an item to give',
    pageSize: 25,
    choices: ["ppsh",
    "mp40",
    "g43",
    "m1garand",
    "svt40",
    "luger",
    "tokarev",
    "webley",
    "bren",
    "bar",
    "sten",
    "stg44",
    "mosin",
    "springfield",
    "thompson",
    "mg42",
    "leeenfield",
    "grenade_us",
    "grenade_ger",
    "smoke_us",
    "smoke_ger",
    "grenade_svt",
    "smoke_svt",
    "rl_piat",
    "rl_m1a1",
    "rl_panzer",
    "cet9",
    "m9",
    "1911",
    "sock",
    "57",
    "de",
    "revolver",
    "sawedoff",
    "shotgun",
    "autoshotgun",
    "drumshotgun",
    "lmga",
    "uzi",
    "mp5",
    "smg",
    "vanas",
    "p90",
    "kar98",
    "ak47",
    "ak12",
    "ak",
    "ar",
    "aug",
    "autosniper",
    "awp",
    "antitank",
    "grenade",
    "grenade_ru",
    "flash",
    "smoke",
    "smoke_ru",
    "defuse",
    "knife",
    "painkillers",
    "taser",
    "syringe",
    "ammo_rifle",
    "ammo_sniper",
    "ammo_pistol",
    "ammo_smg",
    "ammo_shotgun",
    "ammo_special"]
  }, ]).then(async (selected) => {
    item = selected.item;
    fun.playerPrompt(soc, opt.cmd, item)
  })
};

exports.config = {
  enabled: true,
  name: "giveitem",
  view: "GiveItem",
  params: ["steamid", "itemid"]
};
